[package]
name = "rust_audio_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
iced = "0.4.0"
rfd = "0.12.1"
rodio = "0.17.3"
